version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 547091557353.dkr.ecr.eu-north-1.amazonaws.com
  build:
    commands:
      - docker build -t ai .
      - docker tag ai:latest 547091557353.dkr.ecr.eu-north-1.amazonaws.com/ai:latest
  post_build:
    commands:
      - docker push 547091557353.dkr.ecr.eu-north-1.amazonaws.com/ai:latest
      - echo Writing image definitions file...
      - printf '[{"name":"ai","imageUri":"%s"}]' 547091557353.dkr.ecr.us-east-1.amazonaws.com/ai:latest > imagedefinitions.json   
artifacts:
  files: imagedefinitions.json
